class AuthError(Exception):
    """Custom exception for authentication errors."""

    pass


class FaultsAPIError(Exception):
    """Custom exception for faults API errors."""

    pass
